name: Check

on:
  push:
    branches:
      - master
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/package.json"
      - "**/tsconfig.json"
  pull_request:
    branches:
      - master
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/package.json"
      - "**/tsconfig.json"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run check
